<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1900</WarningsNotAsErrors>
    <Deterministic>true</Deterministic>
    <Version>1.7.0</Version>
    <FileVersion>1.7.0.0</FileVersion>
    <AssemblyVersion>1.7.0.0</AssemblyVersion>
  </PropertyGroup>
</Project>
